
export enum EntityType {
  UNKNOWN = 0,
  PERSON = 1,
  MESSAGE = 2,
  RESOURCE = 3,
  SPECIAL = 4,
  LINE = 5,
}

export enum PoiType {
  UNKNOWN = 0,
  LANDMARK = 1,
  MERCHANT = 2,
  USER = 3
}

export enum WorldsEntities {
  MERCHANT_BOUJIN = 1,
  MERCHANT_WESTSIDE_OUTPOST = 2,
  LANDMARK_BELOR_RIFT = 3,
  LANDMARK_VANOR_RIFT = 4,
  LANDMARK_SMAAR_RIFT = 5,
  MERCHANT_CENTRAL_MARKET = 6,
  MERCHANT_BELOR_TOOLS = 7,
  MERCHANT_EASTSIDE_OUTPOST = 8,
  MERCHANT_THIRD_SECTOR = 9,
}

export enum Color {
  RED = 'r',
  GREEN = 'g',
  BLUE = 'b',
  YELLOW = 'y',
  BLACK = 'l',
  WHITE = 'w',
  BROWN = 'n',
  PINK = 'p',
  ORANGE = 'o',
  MINT = 'm',
}

export enum UserUnlocks {
  TELEPORT_KNOWLEDGE = 1,
  SIMPLEWRITE_COLOR_BLUE = 2,
  SIMPLEWRITE_COLOR_BROWN = 3,
  SIMPLEWRITE_COLOR_YELLOW = 4,
  SIMPLEWRITE_COLOR_RED = 5,
  SIMPLEWRITE_COLOR_BLACK = 6,
  SIMPLEWRITE_COLOR_WHITE = 7,
  SIMPLEWRITE_COLOR_PINK = 8,
  SIMPLEWRITE_COLOR_ORANGE = 9,
  SIMPLEWRITE_COLOR_MINT = 10,
  SCANNER_UNKNOWN_REGIONS = 11,
  HANGAR = 12,
  RIFT_MAGNET = 13,
  DEPLOY_PORT = 14,
  LINE_PAINTER = 15,
  LINEPAINT_COLOR_BLUE= 16,
  LINEPAINT_COLOR_BROWN= 17,
  LINEPAINT_COLOR_YELLOW= 18,
  LINEPAINT_COLOR_RED= 19,
  LINEPAINT_COLOR_BLACK= 20,
  LINEPAINT_COLOR_GREEN= 21,
  LINEPAINT_COLOR_PINK= 22,
  LINEPAINT_COLOR_ORANGE= 23,
  LINEPAINT_COLOR_MINT= 24,
  LINEPAINT_THICK_STROKES= 25,
  LINEPAINT_CURVED_LINES= 26,
  TEXT_PAINTER= 27,
  TEXTPAINT_COLOR_BLUE= 28,
  TEXTPAINT_COLOR_BROWN= 29,
  TEXTPAINT_COLOR_YELLOW= 30,
  TEXTPAINT_COLOR_RED= 31,
  TEXTPAINT_COLOR_BLACK= 32,
  TEXTPAINT_COLOR_GREEN= 33,
  TEXTPAINT_COLOR_PINK= 34,
  TEXTPAINT_COLOR_ORANGE= 35,
  TEXTPAINT_COLOR_MINT= 36,
  TEXTPAINT_THICK_STROKES= 37,
  TEXTPAINT_CURVED_LINES= 38,
}
